### ISSUE TITLE
Generate `fromProduct` in the companion object (Scala 3)

### ISSUE THREAD

**Issue by sideeffffect** [com-lihaoyi/unroll#3]
In Scala 3, there exists a method `fromProduct` that gets automatically generated in case classes' companion objects. For backwards compatibility, this methods needs to be explicitly re-implemented and needs to accept tuples of all the necessary arities.

The generated should look something like this
```scala
def fromProduct(p: Product): Person = p.productArity match
  case 2 =>
    Person(
      p.productElement(0).asInstanceOf[...],
      p.productElement(1).asInstanceOf[...],
    )
  case 3 =>
    Person(
      p.productElement(0).asInstanceOf[...],
      p.productElement(1).asInstanceOf[...],
      p.productElement(2).asInstanceOf[...],
    )
  ...
```
Context:
 * https://contributors.scala-lang.org/t/can-we-make-adding-a-parameter-with-a-default-value-binary-compatible/6132/29?u=sideeffffect
 * https://github.com/scala/docs.scala-lang/pull/2788
 * https://github.com/http4s/http4s/pull/7066#issuecomment-1509971972

/cc @armanbilge

**Comment by lihaoyi** [comment]
Done
